### ISSUE TITLE
Apply changes from #81 to the develop branch

### ISSUE THREAD

**Issue by stdevPavelmc** [fibercrypto/skywallet-protob#83]
## The problem
The default branch on this repo is develop, but in issue #82 we merged some changes on master and that changes had to be merged in develop; fibercrypto/skywallet-mcu is using this repo as a submodule, bun on the develop branch, that's the origin of the issue #81, to aid on the fix fibercrypto/skywallet-mcu#342 but on PR #82 the changes was applied to master instead of develop

## Possible Solution
Port the changes applied in #82 to the develop branch

**Comment by olemis** [comment]
fixed in 81be0e9
